### ISSUE TITLE
Bug column in page with bootstrap

### ISSUE THREAD

**Issue by eduardobelchior** [robicch/jQueryGantt#108]
I loaded the chart on my page containing the bootstrap and realized that the graphic has a bug when the page has the bootstrap, how can I get around this? I can not remove the bootstrap

**Comment by robicch** [comment]
I'm sorry, I don't know bootstrap.

**Comment by Patroklo** [comment]
With this I could use the library alongside Bootstrap.

Max is a class added to the first column (the one with the numbers and the pencil).
Max2 is a class added to the second column (the one with the colored balls).

```css

th.gdfColHeader {
  padding: 0px!important;
  vertical-align: middle!important;  
  text-align:center!important;  
}


.gdfColHeader.max {
    max-width: 35px;
}

.gdfColHeader.max2 {
    max-width: 25px;
}
```
